export {
  TemplateConfigSchema,
  TemplateStyleSchema,
  TemplateRegionsSchema,
  SidebarConfigSchema,
  TemplateCompositionSchema,
  SectionIdSchema,
  LayoutShellSchema,
  HeaderStyleSchema,
  SectionStyleSchema,
  SidebarBgModeSchema,
  parseTemplateConfig,
  safeParseTemplateConfig,
  type TemplateConfig,
  type TemplateStyle,
  type TemplateRegions,
  type SidebarConfig,
  type TemplateComposition,
  type SectionId,
  type LayoutShell,
  type HeaderStyle,
  type SectionStyle,
  type SidebarBgMode,
} from "./types";
export { fromEngineConfig } from "./legacy";
